; =============================================================
; KinetiKey — "Old Lock, New Twist"
; Embedded Challenge Spring 2026
;
; Board: Adafruit Circuit Playground Classic (ATmega32u4)
; Accel: LIS3DH (onboard, I2C @ 0x18)
; =============================================================

[env:cpclassic]
platform = atmelavr
board = circuitplay_classic
framework = arduino

lib_deps =
    adafruit/Adafruit LIS3DH@^1.2.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit BusIO@^1.16.2

monitor_speed = 9600

; Extra build flags for optimization
build_flags = -Os
